### ISSUE TITLE
Drag and Drop Support

### ISSUE THREAD

**Issue by jchristman** [google/boardgame.io#56] opened 2017-12-29 12:31 UTC
I have some experience with [React-DnD](https://github.com/react-dnd/react-dnd). Everyone fine if I take a whack at getting a good interface built for drag and drop?

**Comment by nicolodavis** [comment] 2017-12-29 18:19
Sounds good! Just coordinate with @Felizardo on the pull request to add chess pieces.

The plan is to have a single Token component that will implement drag and drop. Presumably we also need a placeholder / receptacle component that can accept draggables as well.

**Comment by Felizardo** [comment] 2017-12-29 18:48
Yep, my current implementation only have implemented animations. I should have it done soon so you can change it later to also add the drag and drop behavior. I will make the animation behavior optional too.

**Comment by jchristman** [comment] 2017-12-29 19:01
Yes hat sounds good - @Felizardo, have you started on a Grid? Is there a commit in your fork I could start from to implement the drop areas? I’m planning on just wrapping a non droppable Grid so that it can be used standalone also.

**Comment by Felizardo** [comment] 2017-12-29 19:06
I haven't yet, because I was reading about React's Context because it will have to inter-operate with the new Token too. 
For instance, if we specify x={1} y={1} z={-2} (z is not mandatory because it can be calculated) in a HexGrid, this will map to a distinct (real) x and y values on the SVG than if the parent is a simple Grid. So we will need to make the token to call a context function to do this coordinate mapping before translating the element to the correct position.

**Comment by nicolodavis** [comment] 2017-12-29 21:56
@Felizardo: I'm not as familiar with SVG, but why does the child component need to know about the parent's context?

I'm imagining that `Grid` or `HexGrid` just passes down the co-ordinates at which the child should render itself through an internal prop that's not used by users directly. You can pass props to children using `React.cloneElement` as demonstrated [here](https://learn.co/lessons/react-this-props-children).

**Comment by Felizardo** [comment] 2017-12-30 13:14
Oh, great! I did not know about the possibility of passing internal prop to
children. I will use this instead, then.

On Fri, Dec 29, 2017 at 7:56 PM, Nicolo John Davis <notifications@github.com

**Comment by nicolodavis** [comment] 2017-12-30 20:24
Closing this as a duplicate of #48 (let's consolidate all discussion there).

**Closed by nicolodavis** 2017-12-30 20:24 UTC
