### ISSUE TITLE
Issues with multiplayer

### ISSUE THREAD

**Issue by janosimas** [google/boardgame.io#188] opened 2018-04-21 21:56 UTC
I having some trouble on how to create the multiplayer version, first let me tell that I have no experience with js so I may be doing something very basic wrong.

The client-only version is working fine.
I tried to create a server and a separated client just like the tutorial, when I debug I can see the `isConnected: true` and `isActive: false`, the current player seems ok too.
No connection error in the console.

When I try to change `endPhase` or `endTurn` nothing happens.

Any help would be great.

**Comment by nicolodavis** [comment] 2018-04-22 03:37
Do you have a repo that I can use to reproduce your problem?

I'll mark this as a duplicate of #187 (let's discuss there).

**Closed by nicolodavis** 2018-04-22 03:37 UTC
