### ISSUE TITLE
Server throwing unhandledRejection

### ISSUE THREAD

**Issue by Toktik** [google/boardgame.io#177] opened 2018-03-28 22:19 UTC
It happens when doing any move. Using 0.21.5.

```
unhandledRejection TypeError: Cannot read property 'allowedMoves' of undefined
    at canMakeMove (C:\projects\playbg\node_modules\boardgame.io\dist\core.js:1481:22)
    at Object.canMakeMove (C:\projects\playbg\node_modules\boardgame.io\dist\core.js:971:14)
    at Socket.<anonymous> (C:\projects\playbg\node_modules\boardgame.io\dist\server.js:1241:26)
    at <anonymous>
```

**Comment by jstacoder** [comment] 2018-03-29 03:04
Is there anyway you could provide the object your passing to `Game`? It would help add context to the error.

**Comment by Stefan-Hanke** [comment] 2018-03-29 05:45
Please add repro steps, or provide your code.

The multiplayer examples utilizing the server seem to work. I've manually deleted _node_modules_ and _dist_, merged latest, ran _npm i_ and then _npm run examples_. Maybe I've missed something, the command is showing that the dev server is using `0.21.5`.

 The code in question fetches the `phase` from the phase map, and calls `allowedMoves` on it. `allowedMoves` is guaranteed to be a function as per [that code](https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L335). Looks like the problem is somewhere in either the phase config or the phase code.

**Comment by Toktik** [comment] 2018-03-29 08:04
Here is the code: https://pastebin.com/a8U4fTBs

I observe that the canMakeMove() is called twice. First time it contains default phase only (not sure what it is), and it throws an error. Second time it contains all my phases.

**Comment by Stefan-Hanke** [comment] 2018-03-29 16:08
Weird. The _default_ phase is only used if no `phases` is passed to the flow. Since the code passes one, you should not see it at all.

Thanks for the code, I'm trying to somehow repro your scenario with it, atm to no avail. Could you share a complete example that demonstrates the issue?

**Comment by nicolodavis** [comment] 2018-04-22 07:15
Closing this for now. @Toktik Feel free to ask at https://gitter.im/boardgame-io/General if you continue to have any problems.

**Closed by nicolodavis** 2018-04-22 07:15 UTC
