### ISSUE TITLE
Random shuffle an array

### ISSUE THREAD

**Issue by philihp** [google/boardgame.io#115] opened 2018-02-18 20:08 UTC
Shuffling a deck of cards, or drawing a tile from a bag is a fairly common operation in lots of games. The [Random API](https://github.com/google/boardgame.io/blob/master/src/core/random.js#L101-L111) should include an operation that deterministically shuffles an array.

@Stefan-Hanke thoughts? I'm happy to take on this feature, if you don't have something in mind already.

**Comment by Stefan-Hanke** [comment] 2018-02-18 20:19
Take it. This is part of #68 (the last bullet point).
I didn't find a nice way to encode the information which array is to be shuffled.

**Comment by nicolodavis** [comment] 2018-02-18 23:00
I'll close this as a duplicate of #68

**Closed by nicolodavis** 2018-02-18 23:00 UTC

**Comment by dondragon2** [comment] 2020-04-02 20:28
I think there is still an issue with the shuffle. I am using the code below and every time a run the simulator for the ai. I get the same order of the deck each time. I assume this should be random but it doesn't seem to be. If I replace it with lodash eg. `_.shuffle(G.deck)` then it is random.

```
const game = Game({
setup: () => ({
      cards: [
          {  face: 'k', suit: 'clubs'},
          {face: 'q', suit: 'diamonds'},
          {  face: 'j', suit: 'hearts'},
          {  face: 'a', suit: 'spades'},
      ],
}),
  moves: {
    move(G, ctx) {
      G.deck = ctx.random.Shuffle(G.deck);
    },
  },
});
```

Am I doing something wrong?
